### ISSUE TITLE
v6: Snapshots + Fluent results in pages always displaying as "Modified"

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#699] opened 2021-04-21 04:45 UTC
This might belong on the Snapshots module, but just raising initially to begin the conversation with @mfendeksilverstripe.

## Steps to reproduce

- Install Silverstripe `v4`, Fluent `dev-master`, Versioned Snapshots `dev-master`
- Created 1 locale (US)
- Created second Locale (MI) with Fallback to US
- Published all existing pages in US locale
- On Home page, use Localisation "Copy 'United States' to other locales"
- **Note:** Home page state is immediately set to a "Modified" in US locale
- Re-publish Home page in US locale
- Switch to MI locale, update content, Publish
- Switch to US locale, Home page is once again in a "Modifidied" state

Any time you update content and publish in one locale, it seems to invalidate the published state of the others.

### Solution One (failure)

I attempted to localise the `Snapshot` model, similar to what we have done on another project (but that project is using Fluent v5):
```
SilverStripe\Snapshots\Snapshot:
  extensions:
    - TractorCow\Fluent\Extension\FluentExtension
  cms_localisation_required: true
```

This did have the **positive effect** of making the History tab localised, however it had no effect the described "Modified" issue.

### Solution Two (failure)

I also attempted to localise both the `Snapshot` and `SnapshotItem` model.

```
SilverStripe\Snapshots\Snapshot:
  extensions:
    - TractorCow\Fluent\Extension\FluentExtension
  cms_localisation_required: true


SilverStripe\Snapshots\SnapshotEvent:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension
  cms_localisation_required: true
```

This had the **positive effect** of _seeming_ to solve the described "Modified" issue, however it had the **negative effect** of making the History tab completely empty in all Locales.

![Screen Shot 2021-04-21 at 4 29 51 PM](https://user-images.githubusercontent.com/505788/115497831-855fca00-a2c0-11eb-8a8a-0f91a259aca2.png)

## Thoughts

I have a feeling that **Solution One** is more the direction we're after, but that perhaps [something] [somewhere] needs to be a bit smarter about how it looks up Snapshot records in order to determine the current state.

**Comment by tractorcow** [comment] 2021-04-22 04:59
History view is still super unreliable in fluent unfortunately; @mfendeksilverstripe any thoughts on this?

**Comment by mfendeksilverstripe** [comment] 2021-05-03 19:22
I'll have a look at this one soon ;-)

**Comment by mfendeksilverstripe** [comment] 2021-06-29 22:39
I was able to reproduce this one @chrispenny . Here is my setup / test case:

![Screen Shot 2021-06-30 at 9 55 18 AM](https://user-images.githubusercontent.com/26395487/123872517-4c5f6800-d989-11eb-83cb-0afe6f6e9d5a.png)

Both Fluent & Snapshots are latest master, no custom configuration (just using default).

I have two locales - EN NZ (default) and EN US (falls back to EN NZ).

I see version snapshot models being created when I interact with the CMS (edits).

![Screen Shot 2021-06-30 at 9 57 05 AM](https://user-images.githubusercontent.com/26395487/123872722-95afb780-d989-11eb-9ce8-dd00fcc4c1d7.png)

## Test flow

Create a published page in EN NZ with one block.

![Screen Shot 2021-06-30 at 9 54 21 AM](https://user-images.githubusercontent.com/26395487/123872777-a7915a80-d989-11eb-81f6-0f42917edeb6.png)

Copy to the US locale.

![Screen Shot 2021-06-30 at 9 58 38 AM](https://user-images.githubusercontent.com/26395487/123872884-c7c11980-d989-11eb-858c-bc4b41db173d.png)

This is the state after copy (same after page reload).

![Screen Shot 2021-06-30 at 10 33 44 AM](https://user-images.githubusercontent.com/26395487/123875973-add60580-d98e-11eb-86eb-2fee671c8a3a.png)

Triggered publish.

![Screen Shot 2021-06-30 at 10 34 25 AM](https://user-images.githubusercontent.com/26395487/123876034-c80fe380-d98e-11eb-9b3a-344f9ab15d61.png)

This is the state after publish (same after page reload).

![Screen Shot 2021-06-30 at 10 34 53 AM](https://user-images.githubusercontent.com/26395487/123876076-da8a1d00-d98e-11eb-9af8-92e03890371f.png)

Switch to US locale, edit and save.

![Screen Shot 2021-06-30 at 10 36 45 AM](https://user-images.githubusercontent.com/26395487/123876258-23da6c80-d98f-11eb-9c17-6dbf2c8e0a39.png)

Switch to NZ locale.

![Screen Shot 2021-06-30 at 10 38 30 AM](https://user-images.githubusercontent.com/26395487/123876348-54baa180-d98f-11eb-9c52-d83e3ac6a29d.png)

I see the publish button indicating the need to publish which is incorrect. I'll keep investigating.

**Comment by mfendeksilverstripe** [comment] 2021-06-29 22:51
This is not caused by the Data state / Fluent lookup. I see that the CMS actions are correctly generated. 

```
$isOnDraft = $this->isOnDraft();
$isPublished = $this->isPublished();
$stagesDiffer = $this->stagesDiffer();
```

All these fields have correct values.

**Comment by mfendeksilverstripe** [comment] 2021-06-30 00:45
@chrispenny I couldn't get the new versioned snapshot admin module to work at all on my local. Here is my composer setup:

```
        "silverstripe/versioned-snapshots": "dev-master",
        "silverstripe/versioned-snapshot-admin": "^0.2.0"
```

I'm getting this error on dev/build:

```
--- Building schema "admin" ---
ERROR [Emergency]: Uncaught SilverStripe\GraphQL\Schema\Exception\SchemaBuilderException: Field className is not allowed on SilverStripe\CMS\Model\SiteTree
IN GET dev/build
Line 1055 in /var/www/mysite/www/vendor/silverstripe/graphql/src/Schema/Schema.php
```

And this error when visiting history tab of the page edit form:

```
[Emergency] Uncaught Error: Call to a member function getTypeNameForClass() on null
GET /admin/pages/history/show/16?l=en_US
Line 45 in /var/www/mysite/www/vendor/silverstripe/versioned-snapshot-admin/src/SnapshotViewerField.php

Source
36     {
37         $data = parent::getSchemaDataDefaults();
38         $record = $this->getSourceRecord();
39 
40         // GraphQL doesn't have any API for "hide ancestor", which we should support at some point
41         // to avoid things like readSiteTree. "Page" is exposed by default
42         $baseClass = $record->baseClass() === SiteTree::class ? 'Page' : $record->baseClass();
43         $config = SchemaBuilder::singleton()->getConfig('admin');
44         $data['data'] = array_merge($data['data'], [
45             'typeName' => $config->getTypeNameForClass($baseClass),
46         ]);
47         return $data;
48     }
49 }
Trace
SilverStripe\SnapshotAdmin\SnapshotViewerField->getSchemaDataDefaults
FormField.php:1528
SilverStripe\Forms\FormField->getSchemaData
HistoryViewerField.php:126
SilverStripe\VersionedAdmin\Forms\HistoryViewerField->getAttributes
FormField.php:733
SilverStripe\Forms\FormField->getAttributesHTML
```

I don't think this is an issue on Fluent module though. This issue should be raised on the `silverstripe/versioned-snapshot-admin` module instead.

cc: @tractorcow

**Comment by mfendeksilverstripe** [comment] 2021-06-30 00:46
The correct Fluent setup for the snapshots should be as follows:

```
SilverStripe\Snapshots\Snapshot:
  cms_localisation_required: 'exact'
  extensions:
    - TractorCow\Fluent\Extension\FluentExtension

SilverStripe\Snapshots\SnapshotItem:
  cms_localisation_required: 'exact'
  extensions:
    - TractorCow\Fluent\Extension\FluentExtension
```

**Comment by mfendeksilverstripe** [comment] 2021-07-01 02:19
@tractorcow I suggest to close this issue as it belongs to the versioned snapshots module.

Also, this was the last issue on my list for the Fluent 6.0.0 tag so if you are happy with what's on master feel free to add the tag ;-)

**Comment by tractorcow** [comment] 2021-07-01 23:30
ok :D

**Closed by tractorcow** 2021-07-01 23:30 UTC
