### ISSUE TITLE
Problem with Siteconfig

### ISSUE THREAD

**Issue by derralf** [tractorcow-farm/silverstripe-fluent#495] opened 2018-11-30 17:27 UTC
Hi,
I've got a weird problem with Siteconfig.

SiteConfig has extension CustomSiteConfig
SiteConfig has fluent extension
(see config below)

Somehow:
- multiple SiteConfig-Rows are created in DB
- for the multiple SiteConfig-Rows localised are created
- the right translations are not found

See Example below.

In the Backend I see the translations (SiteConfig ID 1 gets translated, see below).
But no translation is shown in Frontend or accessible via PHP*. Seems like the CMS thinks the fields are NULL (see below)

```
* e.g.
$SiteConfig = SiteConfig::current_site_config();
var_dump($SiteConfig->MailTo);
```

**mysite.yml**
```
---
Name: myproject
---
...
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extension\CustomSiteConfig
```

**fluentconfig.yml**
```
---
Name: myfluentconfig
After:
  - '#versionedfiles'
  - '#myproject'
---
...
...
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
  translate:
    - 'Title'
    - 'Tagline'
    - 'MailSubject'
    - 'MailThankYouMessage'
    - 'ContactMapInfoWindowTitle'
    - 'ContactMapInfoWindowAddress'
...
...
```

**Table SiteConfig**

|ID|...|MailThankYouMessage|MailTo (untranslated)|Title|
|---|---|---|---|---|
|1|..|Thank you for your request!|mail@domain.com|domain.com|
|2|...|NULL|NULL|Your Site Name|
|3|...|NULL|NULL|Deine Webseite|

The "NULL-Fields" are not shown in CMS, all fields seem to have been filled out.
The following returns NULL in it_IT and de_DE though "mail@domain.com" is shown in Backend in all Languages:
```
$SiteConfig = SiteConfig::current_site_config();
var_dump($SiteConfig->MailTo);
```

**Table SiteConfig_Localised**

|ID|RecordID|Locale|...|MailThankYouMessage|Title|
|---|---|---|---|---|---|
|1|1|en_US|...|Thank you for your request!|domain.com|
|2|2|it_IT|...|NULL|Your Site Name|
|3|1|it_IT|...|Grazie per la vostra richiesta!|domain.com|
|4|3|de_DE|...|NULL|Deine Webseite|
|5|1|de_DE|...|Vielen Dank für Ihre Anfrage|domain.com|

Values from ID 2 and 4 are shown in Frontend.
Values from ID 3 and 5 shown in Backend.
So the shown/displayed values can not be edited. And the values that I can edit are not used/shown in Frontend/PHP.

**Edit:**
If I use `class CustomSiteConfig extends FluentExtension`
I get this Error:
`[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: ALTER TABLE "SiteConfig_Localised" DROP INDEX "Fluent_Record", ADD unique "Fluent_Record" ("RecordID","Locale","RecordID","Locale") 42S21-1060: Duplicate column name 'RecordID'`

**Comment by tractorcow** [comment] 2018-12-03 19:55
Oh, there should only be one siteconfig row; Are you using subsites as well?

**Comment by derralf** [comment] 2018-12-04 14:00
@tractorcow thanks and sorry for bothering you with this

No, no subsites or multisites module.
I did some testing and removed FluentExtension from SiteConfig in yml config. If I now use `class CustomSiteConfig extends FluentExtension` I don't get the `Duplicate column name 'RecordID'`-error anymore. Deleted the SiteConfig* Tables an ran dev/build. All seems to work now. No multiple SiteConfig-rows.

Now it gets strange...

I reverted my config (see first post) an tried to reproduce the "multi-row-error":
Reverted the config, deleted the SiteConfig*-tables, ran dev/build?flush.
At first: No error.
I didn't believe and repeated this multiple times.
While repeating the procedure several times (maybe 10 or 12), the error occurred twice.
I couldn't reliably reproduce the error. But it was there.

I switched back to my "new" config, repeated the test 5 times. As there were no errors I'll stay with my new config. But in the end, I don't know if it really helps...


Finally, a basic question: how do I really apply Fluent correctly to SiteConfig when using a CustomSiteConfig?

Maybe the usage for SiteConfig with CustomSiteConfig should be explained explicitly in the docs. I think the docs are not quite clear here (unless I overlooked something). You can find questions and answers on the net, e.g. here: <https://stackoverflow.com/questions/52650056/how-to-translate-native-siteconfig-with-silverstripe-fluent> But the code snippet from stackoverflow didn't work for me for example.

**Comment by sanderha** [comment] 2019-02-25 15:41
I also seem to have a problem here. If I have multiple extensions that add a few fields to `SiteConfig`, and these extensions all extend `FluentExtension` (to be able to translate their fields), I get the duplicate column error.
Am I doing something wrong here? Can there only be 1 `FluentExtension` on `SiteConfig` at a time?

**Comment by robbieaverill** [comment] 2019-02-25 20:55
>Can there only be 1 FluentExtension on SiteConfig at a time?

Yes that’s correct

**Comment by sanderha** [comment] 2019-02-26 07:21
@robbieaverill Alright so if you want to add fields to SiteConfig which should be translated, you can only add them all at once via one FluentExtension? Can any class only have one instance of `FluentExtension` on it at a time?

**Comment by robbieaverill** [comment] 2019-02-27 00:17
@sanderha yeah that's right. The FluentExtension does the DB manipulation, so you can only have one of it in the chain - otherwise you'll end up with multiple manipulations being performed. You can add extra DB fields to models via extensions as much as you want to, you must however make sure that they are added _before_ FluentExtension runs. You can control this priority using before/after YAML config blocks, or `SilverStripe\Core\Manifest\ModuleManifest.module_priority` config (or both). Hope this helps.

**Comment by sanderha** [comment] 2019-02-27 07:39
Thanks!

**Comment by blueskies79** [comment] 2020-02-02 20:36
Hi folks, I'm having the same issue: I'm randomly suddenly seeing multiple SiteConfig's in the db of a live site. This has already caused some issues, but I wasn't able to track where the duplicates came from. 
I don't really understand what you're saying about the order of the yml issues, @robbieaverill Could you please explain further? Our current setup in yml is this:

---
Name: projectname
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ProjectName\Extensions\CustomSiteConfigExtension
    - TractorCow\Fluent\Extension\FluentExtension

Should one part be moved to an "after" config block? I wouldn't mind doing a pr for a documentation change on this (as this is an essential part and creates some weird issues when it's not set up right), but I'd need to understand it well myself :-)

**Comment by tractorcow** [comment] 2020-02-02 22:12
You aren't using subsites too are you?

**Comment by blueskies79** [comment] 2020-02-02 23:31
No, we aren't using subsites. SS4, latest fluent release. No multisite stuff.

**Comment by tractorcow** [comment] 2020-02-03 03:37
I could see this issue coming up if you had added FluentFilteredExtension accidentally to siteconfig, but you haven't from what I can see. :)

**Comment by blueskies79** [comment] 2020-02-03 08:25
Nope :-(  I can't figure out the trigger (when does the extra SiteConfig record get created?), so I hadn't had enough info to post anything yet. The custom SiteConfig extends from DataExtension, so nothing weird there either, right? But we've had extra SiteConfig records suddenly created in local development environments and in the live site.

**Comment by tractorcow** [comment] 2020-02-04 00:17
SiteConfig gets created when it's requested (SiteConfig::current_site_config()) but for whatever reason is not available. It could be canView(), db query filter, etc... but for some reason the query doesn't retrieve a record, so it scaffolds a new row.

**Comment by blueskies79** [comment] 2020-02-05 08:48
Ok! Hmmmm.... I can verify that we have multiple SiteConfig::current_site_config() calls in our code. So multiple places where this could be triggered. I have it in a set of Page classes and PageController classes: they should be aware of the current locale (without any extra code) and not cause an extra SiteConfig to be created, right?

But then I have a few suspects that might be triggering... We call SiteConfig::current_site_config() in:
- an "extends Controller" class
- an "extends Extension" class 
SilverStripe\ORM\ArrayList:
  extensions:
    - ArrayListExtension
- a plain DataObject class

So if the above don't know the current locale of the site, a new SiteConfig could be triggered? Hmmm... 

Could I do a 
```
Fluent::with_locale('de_DE', function () {
    SiteConfig::current_site_config()->WhatEver
});
```
to ensure the locale is set in those places?

**Comment by tractorcow** [comment] 2020-02-07 04:37
Those should all be fine...

I suggest you debug the extensions you've applied to siteconfig itself.


```php
var_dump(SiteConfig::current_site_config()->getExtensionInstances());
```

**Comment by pascalriedel** [comment] 2020-03-18 15:43
We run into this problem as well and have some steps to reproduce:

- Create a new locale in the fluent admin
- Click 'copy and publish' on any page in your new language 
- View this page

Accessing any SiteConfig property via template or controller calls the current_site_config method that includes a call of make_site_config and actually creates a new SiteConfig.

If you are using Fluent without Subsites saving the specific SiteConfig after creating a new locales would work just fine. In case of using Subsites a possibility to fix that would be to ensure that creating a SiteConfig will only be performed if none exists.

```
public function onBeforeWrite()
{
    SiteConfig::current_site_config()
    if (class_exists(SubsiteState::class)) {
        $siteConfig = DB::prepared_query(
            'SELECT ID, SubsiteID FROM SiteConfig WHERE SubsiteID = ?',
            [SubsiteState::singleton()->getSubsiteId()]
        )->record();

        if ($siteConfig && count($siteConfig)) {
            $this->owner->ID = $siteConfig['ID'];
            $this->owner->RecordID = $siteConfig['ID'];
            $this->owner->SubsiteID = $siteConfig['SubsiteID'];
        }
    } else {
        $siteConfig = DB::query('SELECT ID FROM SiteConfig')->record();

        if ($siteConfig) {
            $this->owner->ID = $siteConfig['ID'];
        }
    }
}
```

**Comment by tractorcow** [comment] 2020-03-19 01:01
Is this a problem with fluent + subsites, but not fluent by itself then? In which case this may be a different problem to the others. Maybe subsite's config is messing with fluent in expected ways.

**Comment by pascalriedel** [comment] 2020-03-20 14:16
No this seems to be a problem without subsites aswell. We came to the same result having duplicate siteconfigs when testing it without subsites. The call of make_site_config is creating a new one instead of saving the existing in the specific language.

**Comment by tractorcow** [comment] 2020-03-23 04:18
Hm how odd. I'll keep an open eye while using fluent to see if I can spot the issue.

**Comment by lekoala** [comment] 2020-03-30 08:28
@tractorcow  i can confirm the issue exists also without subsites (just ran into it myself). i have multiple rows (one per locale) in the SiteConfig table. 

Also, and maybe thats unrelated, I don't have the Title and Tagline fields in SiteConfig_Localised.

No idea why/how/if it's specific to something from my project (that is migrated from SS3, that doesn't help!). If I understand why this happens/happened I'll update this issue.

**Comment by tractorcow** [comment] 2020-04-08 01:39
Ok I think I know what is going on.

`frontend_publish_required` is true for dataobject by default.

we need to default this to false for siteconfig.

Yay!

**Comment by tractorcow** [comment] 2020-04-08 01:49
Fixed with https://github.com/tractorcow-farm/silverstripe-fluent/pull/602

**Closed** 2020-04-08 02:43 UTC
Labels: affects/v4, effort/medium, type/bug
