### ISSUE TITLE
SS4: Error on files with FluentExtension

### ISSUE THREAD

**Issue by sanderha** [tractorcow-farm/silverstripe-fluent#436] opened 2018-07-11 09:28 UTC
I've created a simple `has_one` to `Image` on `Page.php`. I've also defined the relation in `$owns`.
I've applied the `FluentExtension` to `File` aswell, since I want to translate fields on my Image.
On doing upload in a simple upload field, I get this error:
```
ERROR [Notice]: Undefined index: id
IN POST /admin/pages/edit/EditForm/2/field/HeroImage/upload
Line 884 in /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php
```

Will probably debug more later, just thought I'd create an issue for it

**Comment by robbieaverill** [comment] 2018-07-11 21:32
Since files are versioned, I suspect you should be adding the FluentVersionedExtension to File

**Comment by sanderha** [comment] 2018-07-13 12:33
Applying `FluentVersionedExtension` to File seems to give the same error:

```
ERROR [Notice]: Undefined index: id
IN POST /admin/pages/edit/EditForm/1/field/HeroImage/upload
Line 884 in /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php

Source
======
  875:         foreach ($tables as $table) {
  876:             // Make sure that the augmented write is being applied to a table that can be versioned
  877:             $class = isset($manipulation[$table]['class']) ? $manipulation[$table]['class'] : null;
  878:             if (!$class || !$this->canBeVersioned($class)) {
  879:                 unset($manipulation[$table]);
  880:                 continue;
  881:             }
  882: 
  883:             // Get ID field
* 884:             $id = $manipulation[$table]['id']
  885:                 ? $manipulation[$table]['id']
  886:                 : $manipulation[$table]['fields']['ID'];
  887:             if (!$id) {
  888:                 user_error("Couldn't find ID in " . var_export($manipulation[$table], true),
       E_USER_ERROR);
  889:             }
  890: 

Trace
=====
Monolog\ErrorHandler->handleError(8, Undefined index: id, /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php, 884, Array)
Versioned.php:884

SilverStripe\Versioned\Versioned->augmentWrite(Array, , , , , , )
Extensible.php:472

SilverStripe\View\ViewableData->extend(augmentWrite, Array)
DataObject.php:1462

SilverStripe\ORM\DataObject->writeManipulation(File, 2018-07-13 14:32:36, 1)
DataObject.php:1517

SilverStripe\ORM\DataObject->write()
Upload.php:206

SilverStripe\Assets\Upload->loadIntoFile(Array, SilverStripe\Assets\Image, hero)
FileUploadReceiver.php:327

SilverStripe\AssetAdmin\Forms\UploadField->saveTemporaryFile(Array, )
UploadField.php:146

SilverStripe\AssetAdmin\Forms\UploadField->upload(SilverStripe\Control\HTTPRequest)
RequestHandler.php:319

SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, upload)
RequestHandler.php:201

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
RequestHandler.php:225

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
RequestHandler.php:225

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
Controller.php:212

SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
LeftAndMain.php:752

SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest)
AdminRootController.php:123

SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest)
Director.php:361

SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
DetectLocaleMiddleware.php:90

TractorCow\Fluent\Middleware\DetectLocaleMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
InitStateMiddleware.php:54

TractorCow\Fluent\Middleware\InitStateMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
VersionedHTTPMiddleware.php:40

SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
BasicAuthMiddleware.php:68

SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AuthenticationMiddleware.php:61

SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrailingSlashRedirector.php:38

Axllent\TrailingSlash\Middleware\TrailingSlashRedirector->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
CanonicalURLMiddleware.php:156

SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
FlushMiddleware.php:26

SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
RequestProcessor.php:66

SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
SessionMiddleware.php:20

SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AllowedHostsMiddleware.php:60

SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrustedProxyMiddleware.php:176

SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
Director.php:370

SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
HTTPApplication.php:48

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
HTTPApplication.php:66

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
ErrorControlChainMiddleware.php:56

SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)

call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
ErrorControlChain.php:236

SilverStripe\Core\Startup\ErrorControlChain->step()
ErrorControlChain.php:226

SilverStripe\Core\Startup\ErrorControlChain->execute()
ErrorControlChainMiddleware.php:69

SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
HTTPApplication.php:67

SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
HTTPApplication.php:49

SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
index.php:25

ERROR [Notice]: Undefined index: ID
IN POST /admin/pages/edit/EditForm/1/field/HeroImage/upload
Line 886 in /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php

Source
======
  877:             $class = isset($manipulation[$table]['class']) ? $manipulation[$table]['class'] : null;
  878:             if (!$class || !$this->canBeVersioned($class)) {
  879:                 unset($manipulation[$table]);
  880:                 continue;
  881:             }
  882: 
  883:             // Get ID field
  884:             $id = $manipulation[$table]['id']
  885:                 ? $manipulation[$table]['id']
* 886:                 : $manipulation[$table]['fields']['ID'];
  887:             if (!$id) {
  888:                 user_error("Couldn't find ID in " . var_export($manipulation[$table], true),
       E_USER_ERROR);
  889:             }
  890: 
  891:             if ($version < 0 || $this->getNextWriteWithoutVersion()) {
  892:                 // Putting a Version of -1 is a signal to leave the version table alone, despite
       their being no version

Trace
=====
Monolog\ErrorHandler->handleError(8, Undefined index: ID, /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php, 886, Array)
Versioned.php:886

SilverStripe\Versioned\Versioned->augmentWrite(Array, , , , , , )
Extensible.php:472

SilverStripe\View\ViewableData->extend(augmentWrite, Array)
DataObject.php:1462

SilverStripe\ORM\DataObject->writeManipulation(File, 2018-07-13 14:32:36, 1)
DataObject.php:1517

SilverStripe\ORM\DataObject->write()
Upload.php:206

SilverStripe\Assets\Upload->loadIntoFile(Array, SilverStripe\Assets\Image, hero)
FileUploadReceiver.php:327

SilverStripe\AssetAdmin\Forms\UploadField->saveTemporaryFile(Array, )
UploadField.php:146

SilverStripe\AssetAdmin\Forms\UploadField->upload(SilverStripe\Control\HTTPRequest)
RequestHandler.php:319

SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, upload)
RequestHandler.php:201

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
RequestHandler.php:225

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
RequestHandler.php:225

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
Controller.php:212

SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
LeftAndMain.php:752

SilverStripe\Admin\LeftAndMain->handleRequest(SilverStripe\Control\HTTPRequest)
AdminRootController.php:123

SilverStripe\Admin\AdminRootController->handleRequest(SilverStripe\Control\HTTPRequest)
Director.php:361

SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
DetectLocaleMiddleware.php:90

TractorCow\Fluent\Middleware\DetectLocaleMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
InitStateMiddleware.php:54

TractorCow\Fluent\Middleware\InitStateMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
VersionedHTTPMiddleware.php:40

SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
BasicAuthMiddleware.php:68

SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AuthenticationMiddleware.php:61

SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrailingSlashRedirector.php:38

Axllent\TrailingSlash\Middleware\TrailingSlashRedirector->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
CanonicalURLMiddleware.php:156

SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
FlushMiddleware.php:26

SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
RequestProcessor.php:66

SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
SessionMiddleware.php:20

SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AllowedHostsMiddleware.php:60

SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrustedProxyMiddleware.php:176

SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
Director.php:370

SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
HTTPApplication.php:48

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
HTTPApplication.php:66

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
ErrorControlChainMiddleware.php:56

SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)

call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
ErrorControlChain.php:236

SilverStripe\Core\Startup\ErrorControlChain->step()
ErrorControlChain.php:226

SilverStripe\Core\Startup\ErrorControlChain->execute()
ErrorControlChainMiddleware.php:69

SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
HTTPApplication.php:67

SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
HTTPApplication.php:49

SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
index.php:25

ERROR [User Error]: Couldn't find ID in array (
  'fields' => 
  array (
    'Name' => 'spacewalk-v2.jpg',
    'Title' => 'spacewalk v2',
    'RecordID' => '68',
    'Locale' => 'da_DK',
  ),
  'command' => 'insert',
  'class' => 'SilverStripe\\Assets\\File',
  'where' => 
  array (
    '"File_Localised"."RecordID"' => '68',
    '"File_Localised"."Locale"' => 'da_DK',
  ),
)
IN POST /admin/pages/edit/EditForm/1/field/HeroImage/upload
Line 888 in /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php

Source
======
  879:                 unset($manipulation[$table]);
  880:                 continue;
  881:             }
  882: 
  883:             // Get ID field
  884:             $id = $manipulation[$table]['id']
  885:                 ? $manipulation[$table]['id']
  886:                 : $manipulation[$table]['fields']['ID'];
  887:             if (!$id) {
* 888:                 user_error("Couldn't find ID in " . var_export($manipulation[$table], true),
       E_USER_ERROR);
  889:             }
  890: 
  891:             if ($version < 0 || $this->getNextWriteWithoutVersion()) {
  892:                 // Putting a Version of -1 is a signal to leave the version table alone, despite
       their being no version
  893:                 unset($manipulation[$table]['fields']['Version']);
  894:             } elseif (empty($version)) {

Trace
=====
SilverStripe\Dev\CliDebugView->renderTrace()
DetailedErrorFormatter.php:119

SilverStripe\Logging\DetailedErrorFormatter->output(256, Couldn't find ID in array (
  'fields' => 
  array (
    'Name' => 'spacewalk-v2.jpg',
    'Title' => 'spacewalk v2',
    'RecordID' => '68',
    'Locale' => 'da_DK',
  ),
  'command' => 'insert',
  'class' => 'SilverStripe\\Assets\\File',
  'where' => 
  array (
    '"File_Localised"."RecordID"' => '68',
    '"File_Localised"."Locale"' => 'da_DK',
  ),
), /Applications/MAMP/htdocs/kirklarsen/vendor/silverstripe/versioned/src/Versioned.php, 888, )
DetailedErrorFormatter.php:54

SilverStripe\Logging\DetailedErrorFormatter->format(Array)
AbstractProcessingHandler.php:35

Monolog\Handler\AbstractProcessingHandler->handle(Array)
Logger.php:337

Monolog\Logger->addRecord(550, Fatal Error (E_USER_ERROR): Couldn't find ID in array (
  'fields' => 
  array (
    'Name' => 'spacewalk-v2.jpg',
    'Title' => 'spacewalk v2',
    'RecordID' => '68',
    'Locale' => 'da_DK',
  ),
  'command' => 'insert',
  'class' => 'SilverStripe\\Assets\\File',
  'where' => 
  array (
    '"File_Localised"."RecordID"' => '68',
    '"File_Localised"."Locale"' => 'da_DK',
  ),
), Array)
Logger.php:518

Monolog\Logger->log(550, Fatal Error (E_USER_ERROR): Couldn't find ID in array (
  'fields' => 
  array (
    'Name' => 'spacewalk-v2.jpg',
    'Title' => 'spacewalk v2',
    'RecordID' => '68',
    'Locale' => 'da_DK',
  ),
  'command' => 'insert',
  'class' => 'SilverStripe\\Assets\\File',
  'where' => 
  array (
    '"File_Localised"."RecordID"' => '68',
    '"File_Localised"."Locale"' => 'da_DK',
  ),
), Array)
ErrorHandler.php:180

Monolog\ErrorHandler->handleFatalError()
```

**Comment by TheBnl** [comment] 2018-09-08 10:43
I had the same issue, but you need to make sure to include the extension after the versioned extension is added. I added the module that i was using the dataobject from into the after statement like:
```yml
---
Name: extensions
after: ['#versionedfiles', '#pageslices']
---
Broarm\PageSlices\PageSlice:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension
```
So if your using a dataobject from another module it is important to set that in the after statement as well.

**Comment by prettytamben** [comment] 2020-04-03 12:20
Hey @TheBnl, could you pls elaborate? I have the same issue. 
I have several dataobjects, I have several extended Page types. The only thing is not translated is the File

This is how my fluent.yml looks like 

`---
Name: nwye-fluent
After: '#versionedfiles'
---
SilverStripe\Assets\File:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension
TractorCow\Fluent\Extension\FluentDirectorExtension:
  detect_locale: true  
SiteTree:
  extensions:
    - TractorCow\Fluent\Extension\FluentFilteredExtension
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Agenda:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Slider:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Gallery:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Testimonial:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Feature:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Grades:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'`

**Comment by TheBnl** [comment] 2020-04-03 17:53
Could you put the content of the file in a code block? YML files are pretty strict on the formatting. This looks like the extension is places before the yml header?

**Comment by prettytamben** [comment] 2020-04-03 18:10
<pre>---
Name: nwye-fluent
After: '#versionedfiles'
---
SilverStripe\Assets\Image:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension
TractorCow\Fluent\Extension\FluentDirectorExtension:
  detect_locale: true  
SiteTree:
  extensions:
    - TractorCow\Fluent\Extension\FluentFilteredExtension
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Agenda:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Slider:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Gallery:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Testimonial:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Feature:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'
Grades:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'`

**Comment by tractorcow** [comment] 2020-04-09 04:50
I've had this issue before. It was caused by adding FluentVersionedExtension to the file class BEFORE versioned.

In `develop` branch I added a check in augmentDatabase() to warn users if this occurred.

```
    public function augmentDatabase()
    {
        // Safety check: This extension is added AFTER versioned
        $seenVersioned = false;
        foreach ($this->owner->getExtensionInstances() as $extension) {
            // Must see versioned
            if ($extension instanceof Versioned) {
                $seenVersioned = true;
            } elseif ($extension instanceof self) {
                if (!$seenVersioned) {
                    throw new LogicException(
                        "FluentVersionedExtension must be added AFTER Versioned extension. Check "
                        . get_class($this->owner)
                    );
                }
            }
        }

        parent::augmentDatabase();
    }
```

Unfortunately due to the way that fluent rewrites versioned queries, it's necessary for this order.

**Comment by tractorcow** [comment] 2020-04-09 04:52
Sorry I just realised @TheBnl actually said this already

> I had the same issue, but you need to make sure to include the extension after the versioned extension is added. I added the module that i was using the dataobject from into the after statement like:

credit to them for the catch :)

**Comment by tractorcow** [comment] 2020-04-09 04:55
@prettytamben if you are having trouble you should set an explicit field list for what you want localised.

E.g.

```
SilverStripe\Assets\File:
  translate:
    - Title
```

I would NOT try to localise any fields that relate to actual storage (e.g. Name, ParentID) or you will probably break the storage of the record.

**Comment by prettytamben** [comment] 2020-04-09 06:21
Thanks for the suggestions, I'll take a look.

**Comment by tractorcow** [comment] 2020-04-13 23:20
The original issue of sorting has been taken care of with the recent updates. I'll close this ticket for now and we can re-open if you have further issues @prettytamben :)

**Closed by tractorcow** 2020-04-13 23:20 UTC
Labels: affects/v4, feedback-required/author, type/bug
