### ISSUE TITLE
Bug: FluentSiteTreeExtension updateLink() doubles domain-prefix

### ISSUE THREAD

**Issue by Marimchen** [tractorcow-farm/silverstripe-fluent#730] opened 2021-10-14 11:56 UTC
FluentSiteTreeExtension updateLink() doesn't check, if the Link is already absolute or if the link already has it's domain-prefix.

This happens when updateLink() is called twice for some reason. In my case the product-class from silvershop-core called it again after this was already called and handled in SiteTree's Link-method. This results in links like this: 

https://at.my-shop.local/https://at.my-shop.local/category1/produktABC/

Related to: https://github.com/silvershop/silvershop-core/issues/772

**Comment by tractorcow** [comment] 2021-10-17 19:37
Hi @Marimchen thanks for the report; It's certainly an issue if this occurs.

Ideally modules would refrain from invoking the method multiple times; I might consider this an issue that should be fixed in silvershop, not a bug in Fluent.

I won't close this issue straight away, in case we determine there is an issue in Fluent that should also be resolved.

Given this PR https://github.com/silvershop/silvershop-core/pull/773 is merged, can you confirm the issue is solved in silvershop?

**Comment by Marimchen** [comment] 2022-07-29 10:09
it's in dev-master right now but not in the latest release yet

**Comment by tractorcow** [comment] 2022-07-31 20:22
it's in 3.0.4 now https://github.com/silvershop/silvershop-core/releases/tag/3.0.4

**Closed by tractorcow** 2022-07-31 20:22 UTC
